### ISSUE TITLE
SQL actions добавить поле role id

### ISSUE THREAD

**Issue by MaxBro12** [NightCodeTeam/Free-Fly-Bot#74]
В таблице onjoin_actions добавить поле role_id 

Задачи:
1. При создании таблицы чтобы создавалась эта колонка
2. Скрипт обновления таблицы чтобы не мучиться с переносом данных
3. Обновить классы данных, а так же запросы в sql с учетом нового поля

**Comment by iogannes** [comment]
класс данных и sql запросы скорректированы, НО скорее всего это не работает, потому что то что торчит "наружу" написано под старый датакласс...
